Run: List
	bin/List.out

List: Main Logs
	g++ -o bin/List.out bin/List_main.o bin/Logs.o

Main: List_main.cpp List.h
	g++ -c -o bin/List_main.o List_main.cpp

Logs: Logs.cpp List.h
	g++ -c -o bin/Logs.o Logs.cpp